In [2]:
import numpy as np

Q-1 Create a null vector of size 10 but the fifth value which is 1.

In [3]:
# n = np.zeros(10)
n = np.empty(10)
n
n = np.nan*n
n[4] = 1
n

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

Q-2 Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
# a = int(input("Enter no. of rows: "))
# b = int(input("Enter no. of columns: "))
a,b = map(int,input("Enter No. rows and Col. : ").split())
arr = np.random.random((a,b))
print(arr)

# AVG of Array
np.mean(arr)

Q-3Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.
Eg.-

[[1,1,1,1],  
[1,0,0,1],  
[1,0,0,1],  
[1,1,1,1]]  


In [ ]:
def create_arr(a,b):
    arr = np.ones((a,b))
    arr[1:-1,1:-1] = 0

    return arr


a,b = map(int,input("Enter No. rows and Col. : ").split())
ar = create_arr(a,b)
ar

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

Q-4 Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
arr = np.linspace(0,1,12)
arr = arr[1:-1]
arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

Q-5 Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
# Identity matricx is a square mattrix, means no of rows and columns will always be same.
# Here shape given 3,4 so identuty matrix not possible.

# using identity
i = np.identity(4)
i

# using eye(N,M=None,K=0,dtype=float) n=row, m=col, k=shif of 1 in diagnoal
e = np.eye(4)
e
# use of shift
e = np.eye(3,4)
e
e = np.eye(4,k=1) # shift diagonal of 1 upward 
e


array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

Q-6: Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
matrix = np.zeros((5,5))
matrix+=np.arange(5)
matrix

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

Q-7: Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

point = np.array([2,3])

In [ ]:
point = np.array([2,3])
arr = np.random.randint(1,100,size=(10,2))
print(arr)

distance = np.sqrt(np.sum((arr-point)**2,axis=1))
type(distance)
distance.astype(np.int32)

[[43 37]
 [34 36]
 [93 19]
 [32 46]
 [78 71]
 [25 98]
 [43 75]
 [46 16]
 [61 64]
 [57 29]]


array([ 53,  45,  92,  52, 101,  97,  82,  45,  84,  60], dtype=int32)

Q-8: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
# arr = np.random.random((6,7,8))
# arr
# np.unravel_index(99,arr.shape)
np.unravel_index(99,(6,7,8))


(np.int64(1), np.int64(5), np.int64(3))

Q-9: Arrays
You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.

Input Format:

A single line of input containing space separated numbers.

Output Format:

Print the reverse NumPy array with type float.

Example 1:

Input:

1 2 3 4 -8 -10
Output:

[-10.  -8.   4.   3.   2.   1.]

In [ ]:
arr = input("Enter space separated list of numbers: ").strip().split()


In [ ]:
newarr = np.array(arr,dtype=np.float32)
newarr[::-1]

array([7., 7., 7.], dtype=float32)

Q-10: Elements count  
Count the number of elements of a numpy array.  

Example 1:  

Input:  

np.array([])  
Output:  

elements_count :  0  
Example 2:  

Input:   

np.array([1, 2])  
Output:  

elements_count :  2  



In [ ]:
arr = np.array([1,2,2,12,12,21])
arr.size

arr = np.ones((23,32))
arr.size



736

Q-11: Softmax function
Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.
  
$$
\sigma(\mathbf{z})_i = \frac{e^{z_i}}{\sum_{j=1}^{K} e^{z_j}}
$$  

https://en.wikipedia.org/wiki/Softmax_function  

Example 1:  

Input:  

[86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]  

Output:  
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 
       5.05514197e-22, 1.50974911e-22]  


Example 2:  

Input:  
[33.17344305, 45.61961654, 82.05405781, 80.9647098,  68.82830233, 91.52064278]  

Output:  
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]  


In [ ]:
def softmax(array):
    if type(array)!=np.ndarray:
        raise TypeError("requires Numpy array")
    elif array.ndim !=1:
        raise ValueError(f"Expected a 1d array, but received a {array.ndim}d array")

    s =np.sum(np.exp(array))
    return np.exp(array)/s

softmax(np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]))
softmax(np.array([33.17344305, 45.61961654, 82.05405781, 80.9647098,  68.82830233, 91.52064278]))
# softmax(np.array([[1,2],[3,4]]))

array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

Q-12: Vertical stack  
Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.  

Example 1:  

Input:  

a= [[0 1 2 3 4]  
 [5 6 7 8 9]]  

b= [[1 1 1 1 1]  
 [1 1 1 1 1]]  
Output:  

[[0 1 2 3 4]  
 [5 6 7 8 9]  
 [1 1 1 1 1]  
 [1 1 1 1 1]]  
Example 2:  

Input:  

a= [[0 1 2 3 4]  
 [5 6 7 8 9]]  

b= [[1 1 1 1 1]  
 [1 1 1 1 1]]  

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]  
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]   
Output:  

[[0.         1.         2.         3.         4.        ]  
 [5.         6.         7.         8.         9.        ]  
 [1.         1.         1.         1.         1.        ]  
 [1.         1.         1.         1.         1.        ]  
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]  
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]  

In [ ]:
def VerticalStack(*args):
    for array in args:
        if not isinstance(array,np.ndarray):
            raise TypeError("Requires numpy array")
    return np.vstack(args)
              
a= np.array([[0,1,2,3,4],[5,6,7,8,9]] )

b= np.array([[1,1,1,1,1],[1,1,1,1,1]])

VerticalStack(a,b)


c = np.arange(10).reshape(2,5)
d = np.ones(5)
VerticalStack(a,b,c,d)
e = np.repeat(1,10).reshape(2,-1)
e
VerticalStack(a,b,c,d,e)
# a = np.arange(10).reshape(2, -1)
# a

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Q-13: Dates
Create a python function named date_array that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: 2022-12-6. The end date should be included and for simplicity, choose dates from a same year.  

Example 1:  

Input:  

date_array(start = '2020-09-15', end = '2020-09-25')  
Output:  
  
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',  
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',  
 '2020-09-23', '2020-09-24', '2020-09-25']  
Example 2:  
  
Input:  

date_array(start = '2022-12-01', end = '2022-12-06')  
Output:  

['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']  
Example 3:  

Input:  
  
date_array(start = '2020-11-25', end = '2020-11-30')  
Output:  

['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',  
 '2020-11-29', '2020-11-30']  

  

In [ ]:
from datetime import datetime,timedelta
# import datetime
def date_array(start:str,end:str):
    '''date_array that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: 2022-12-6.(yy-mm-dd)'''
    if type(start) != str | type(end)!= str:
        raise TypeError("s tart and end must be strings")
    try:
        # Convert strings to datetime objects
        start_date = datetime.strptime(start, "%Y-%m-%d")
        end_date = datetime.strptime(end, "%Y-%m-%d")
    except ValueError:
        raise ValueError("Date format must be YYYY-MM-DD")

    cur = start_date
    list_date = []
    while cur<=end_date:
        list_date.append(cur)
        cur += timedelta(days=1)

    return np.array(list_date,dtype='datetime64[D]')


date_array(start = '2022-11-01', end = '2022-12-06')  



array(['2022-11-01', '2022-11-02', '2022-11-03', '2022-11-04',
       '2022-11-05', '2022-11-06', '2022-11-07', '2022-11-08',
       '2022-11-09', '2022-11-10', '2022-11-11', '2022-11-12',
       '2022-11-13', '2022-11-14', '2022-11-15', '2022-11-16',
       '2022-11-17', '2022-11-18', '2022-11-19', '2022-11-20',
       '2022-11-21', '2022-11-22', '2022-11-23', '2022-11-24',
       '2022-11-25', '2022-11-26', '2022-11-27', '2022-11-28',
       '2022-11-29', '2022-11-30', '2022-12-01', '2022-12-02',
       '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06'],
      dtype='datetime64[D]')

Q-14: Subtract the mean of each row from a matrix.

In [30]:
matrix = np.random.random((3,5))
print(matrix)
# mean = np.mean(matrix,axis=1,keepdims=True)
mean = matrix.mean(axis=1,keepdims=True)
print(mean)
mean-matrix


[[0.84035907 0.53285349 0.19934164 0.30690894 0.46364909]
 [0.24716858 0.9580147  0.00762612 0.28749242 0.3667617 ]
 [0.61950434 0.76970982 0.54764277 0.50694047 0.42257907]]
[[0.46862244]
 [0.3734127 ]
 [0.57327529]]


array([[-0.37173662, -0.06423104,  0.2692808 ,  0.1617135 ,  0.00497336],
       [ 0.12624413, -0.584602  ,  0.36578659,  0.08592028,  0.006651  ],
       [-0.04622905, -0.19643452,  0.02563253,  0.06633483,  0.15069622]])

Q-15: Swap column-1 of array with column-2 in the array.

In [56]:
matrix = np.random.random((4,5))
matrix

array([[0.98947954, 0.13637539, 0.79576354, 0.05783757, 0.24494608],
       [0.48444786, 0.90995328, 0.86194436, 0.23296489, 0.13755652],
       [0.91272346, 0.74687996, 0.84022796, 0.54564786, 0.55521793],
       [0.57708742, 0.89015701, 0.73102631, 0.50390008, 0.78607292]])

In [57]:
# 1st way
matrix[:,[1,0,2,3]]

# 2nd way
temp = matrix
temp[:,[0,1]]=temp[:,[1,0]]
temp

array([[0.13637539, 0.98947954, 0.79576354, 0.05783757, 0.24494608],
       [0.90995328, 0.48444786, 0.86194436, 0.23296489, 0.13755652],
       [0.74687996, 0.91272346, 0.84022796, 0.54564786, 0.55521793],
       [0.89015701, 0.57708742, 0.73102631, 0.50390008, 0.78607292]])

Q-16: Replace odd elements in arrays with -1.

In [71]:
matrix = np.linspace(1,100,100,dtype='int32')
matrix


array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100], dtype=int32)

In [ ]:
matrix[matrix%2!=0]=-1  # change the array
matrix
# np.where(): we can use where also: it create new array: doesnot changes existing
# np.where(matrix%2!=0,0,matrix)


array([ -1,   2,  -1,   4,  -1,   6,  -1,   8,  -1,  10,  -1,  12,  -1,
        14,  -1,  16,  -1,  18,  -1,  20,  -1,  22,  -1,  24,  -1,  26,
        -1,  28,  -1,  30,  -1,  32,  -1,  34,  -1,  36,  -1,  38,  -1,
        40,  -1,  42,  -1,  44,  -1,  46,  -1,  48,  -1,  50,  -1,  52,
        -1,  54,  -1,  56,  -1,  58,  -1,  60,  -1,  62,  -1,  64,  -1,
        66,  -1,  68,  -1,  70,  -1,  72,  -1,  74,  -1,  76,  -1,  78,
        -1,  80,  -1,  82,  -1,  84,  -1,  86,  -1,  88,  -1,  90,  -1,
        92,  -1,  94,  -1,  96,  -1,  98,  -1, 100], dtype=int32)

Q-17: Given two arrays of same shape make an array of max out of two arrays. (Numpy way)  
a=np.array([6,3,1,5,8])  
b=np.array([3,2,1,7,2])  

Result-> [6 3 1 7 8]  

In [23]:
a=np.array([6,3,1,5,8])  
b=np.array([3,2,1,7,2]) 
a[b>a] = b[a<b]
a

array([6, 3, 1, 7, 8])

### `Q-18` Answer the following questions on the given array:

1. Fetch every alternate column of the array.
2. Normalize the given array.

Reference: [Normalization (Statistics)](https://en.wikipedia.org/wiki/Normalization_\(statistics\))

There are different forms of normalization. For this question, use the following formula:

$$
X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}
$$



What is Normalization?

Normalization is the process of converting values in a dataset to a common range, usually 0 to 1.

It is useful when different columns have very different scales.

In [10]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[3123, 4664, 1146, 3230, 7234],
       [9258, 8799,  477,  177, 4732],
       [2765, 7709, 5211, 7697, 3509],
       [2284, 1362, 9450, 1354, 4442],
       [5163, 8236,   60, 6493, 8052],
       [ 217, 3949, 1708, 3975, 1226],
       [9719, 5903, 5057, 7745, 9596],
       [2264, 8028, 5585, 9483, 2854]], dtype=int32)

In [8]:
# Fetching every alternate col
arr1[:,::2] 

array([[6544, 5829,  350],
       [2887, 9006, 6605],
       [6667,  906, 2378],
       [7472, 6096, 5247],
       [ 272,   79, 8832],
       [9710, 4846, 9605],
       [3146,  896, 2241],
       [5356, 5769, 9244]], dtype=int32)

In [11]:
# normalize the array 
def normalize(array):
    return (array-np.min(array))/(np.max(array)-np.min(array))


normalize(arr1)

array([[0.31711357, 0.4766539 , 0.112434  , 0.32819132, 0.74272699],
       [0.95227249, 0.90475204, 0.04317217, 0.01211306, 0.48369396],
       [0.28004969, 0.79190392, 0.53328502, 0.79066156, 0.3570763 ],
       [0.23025158, 0.13479656, 0.97215033, 0.13396832, 0.45367015],
       [0.52831556, 0.84646444, 0.        , 0.66601097, 0.82741485],
       [0.01625427, 0.40262967, 0.17061808, 0.40532146, 0.12071643],
       [1.        , 0.60492805, 0.51734134, 0.79563102, 0.98726576],
       [0.22818097, 0.82493012, 0.57200538, 0.97556683, 0.2892639 ]])

Q-19: Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array

Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12  
Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

In [24]:
def Nth_largest(array,num):
    if array.ndim>1:
        raise TypeError("Requires 1d array")
        
    if num < 1 or num>array.size:
        raise ValueError("Nth Value should be less than and equal t0 array's length")

    return np.sort(array,descending=True)[num-1]

arr=np.random.randint(low=1,high=200,size=20) 
print(arr)


[ 62 182  25 185 128  52  11  39  13  14  80   2  13 170   6 129  30 135
 194  56]


In [25]:
Nth_largest(arr,4)

np.int32(170)

Q-20: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.  
Input: a = np.array([1,2,3])  
Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])  

| Function      | What it repeats     | Example               |
| ------------- | ------------------- | --------------------- |
| `np.repeat()` | Each **element**    | `[1,1,1,2,2,2,3,3,3]` |
| `np.tile()`   | The **whole array** | `[1,2,3,1,2,3,1,2,3]` |


In [ ]:
a = np.array([1,2,3])
new = np.repeat(a,np.size(a))
# np.concatenate((new,a,a,a))
# np.hstack([np.repeat(a, 3), np.tile(a, 3)])
np.concatenate((new, np.tile(a, np.size(a))))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])